# Generated by Django 4.2.6 on 2023-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'deleted'), (1, 'active')], default=1)),
                ('is_completed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('removed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'task_master',
                'managed': True,
            },
        ),
    ]
