# Generated by Django 4.2.6 on 2023-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
