# Generated by Django 4.2.6 on 2023-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_master_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
